site_name: COSMOPlat-平台指南
nav:
#    - '目录': '目录.md'
    - '基础知识速成':
        - 'linux':
            - 'linux-bash': '基础知识/linux/Linux-bash.md'
            - 'linux-command': '基础知识/linux/Linux-command.md'
            - 'linux-filesystem': '基础知识/linux/Linux-filesystem.md'
            - 'linux-shellscript': '基础知识/linux/Linux-shellscript.md'
        - 'Docker':
            - '基础概念': '基础知识/docker/基础概念.md'
            - '命令行': '基础知识/docker/命令行.md'
            - '镜像构建和使用': '基础知识/docker/镜像构建和使用.md'
            - '镜像构建最佳实践': '基础知识/docker/镜像构建最佳实践.md'
        - 'Kubernetes':
            - 'Kubernetes介绍': '基础知识/kubernetes/Kubernetes介绍.md'
            - '基础概念': '基础知识/kubernetes/基础概念.md'
            - '模块介绍': '基础知识/kubernetes/模块介绍.md'
            - '命令行': '基础知识/kubernetes/命令行.md'
            - '操作实践': '基础知识/kubernetes/操作实践.md'
#    - '开发者平台操作手册': '开发者平台.md'
    - '运维人员指南':
        - '常见功能场景': '常见功能场景.md'
    - '常见问题汇总':
        - '应用上云': '应用上云.md'
        - '构建镜像': '构建镜像.md'
        - '控制台': '控制台.md'
        - 'CI/CD':
            - '代码集成': '代码集成.md'
            - '构建部署': '构建部署.md'
    - '开发人员指南':
        - '概述': '开发指南/概述.md'
        - '平台使用手册': '开发指南/平台使用手册.md'
        - 'SpringCloud微服务docker容器化最佳实践': '开发指南/SpringCloud微服务docker容器化最佳实践.md'
        - 'python开发者的docker之旅': '开发指南/python开发者的docker之旅.md'
        - 'php开发者的docker之旅': '开发指南/php开发者的docker之旅.md'
        - '用docker构建angular前端应用': '开发指南/用docker构建angular前端应用.md'

theme:
  name: 'material'
