site_name: COSMOPlat-平台指南
pages:
    - '目录': '目录.md'
    - '开发者平台': '开发者平台.md'
    - '开发指南':
        - '概述': '开发指南/概述.md'
        - '平台使用手册': '开发指南/平台使用手册.md'
        - 'SpringCloud微服务docker容器化最佳实践': '开发指南/SpringCloud微服务docker容器化最佳实践.md'
        - 'python开发者的docker之旅': '开发指南/python开发者的docker之旅.md'
        - 'php开发者的docker之旅': '开发指南/php开发者的docker之旅.md'
        - '用docker构建angular前端应用': '开发指南/用docker构建angular前端应用.md'

theme: readthedocs
